name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix: 
        os: [ubuntu-20.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: task_manager

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          sleep 10

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        env:
          DB_URL: "jdbc:postgresql://localhost:5432/task_manager"
          DB_USER: ${{ secrets.POSTGRE_ID }}
          DB_PASSWORD: ${{ secrets.POSTGRE_MDP }}
        run: mvn test

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      - name: Upload JaCoCo Coverage Report
        if: success()
        run: |
          echo "Uploading JaCoCo Coverage Report..."
          cat target/site/jacoco/index.html >> $GITHUB_STEP_SUMMARY
          echo "Coverage report is available in the summary."
